### ISSUE TITLE
PDF set password error

### ISSUE THREAD

**Issue by ghost** [benbahrenburg/PDFUtilities#2]
[pdfPassword.zip](https://github.com/benbahrenburg/PDFUtilities/files/1122459/pdfPassword.zip)

**Comment by benbahrenburg** [comment]
Sorry you are running into an issue.  To best help I need more information on how you are using the library, and what methods you are calling.  Please provide a code sample of how you're using the library.

**Comment by ghost** [comment]
Ok, just 3 min

**Comment by ghost** [comment]
[PDFUtil.zip](https://github.com/benbahrenburg/PDFUtilities/files/1122609/PDFUtil.zip)

**Comment by benbahrenburg** [comment]
Looks like kCGPDFContextUserPassword and kCGPDFContextOwnerPassword cannot be set separately in 10.3.  I'll open a radar.  Easy enough work around using the below example for now.

~~~
class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let pdfURL = Bundle.main.bundleURL.appendingPathComponent("test.pdf")
        let fm = FileManager.default
        let docsurl = try! fm.url(for:.documentDirectory, in: .userDomainMask, appropriateFor: nil, create: false)
        let pdPassfURL = docsurl.appendingPathComponent("pass.pdf")

        do {
            let password = PDFDocumentPasswordInfo(userPassword: "1111", ownerPassword: "1111")
            let data = try PDFUtilities.addPassword(fileURL: pdfURL, documentPasswordInfo: password)
            
            try data?.write(to: pdPassfURL)
            
            
        } catch {
            print(error.localizedDescription)
        }
    }
}

~~~

**Comment by ghost** [comment]
@benbahrenburg Thank you much!
You're genius!
