### ISSUE TITLE
How to open unlocked PDF?

### ISSUE THREAD

**Issue by ghost** [benbahrenburg/PDFUtilities#3]
Hi, show please the full way to open the locked PDF.
For example: I set the pin to PDF file, I want to check if the PDF file has password, to check if is the correct password from more passwords and to open just document, to show all content.

And last, remove password document. That's last step.

1. I tried that:

>  let password = PDFDocumentPasswordInfo(userPassword: text, ownerPassword: text)
>                 if let imagesForPreview = PDFConverters.pdfToImages(data: pdfData, documentPasswordInfo: password) {
> }
> 

That's open the document if you put the correct password, in other case, if password is incorrect, the app crash's with error:
**fatal error: Can't form Range with upperBound < lowerBound**
![screen shot 2017-07-06 at 11 56 03 am](https://user-images.githubusercontent.com/22445295/27903469-23cb89fe-6242-11e7-9b8e-38cbe66f4804.png)

Regards

**Comment by ghost** [comment]
**With that error, I modified old crash's method:**
![27903469-23cb89fe-6242-11e7-9b8e-38cbe66f4804](https://user-images.githubusercontent.com/22445295/27903687-d6e107bc-6242-11e7-8484-fff2cc0412a9.png)

**with:**

```
    class open func pdfToImages(pdf: CGPDFDocument, documentPasswordInfo: PDFDocumentPasswordInfo? = nil) -> [UIImage]? {
        var output = [UIImage]()
        let pdf = (documentPasswordInfo != nil) ? PDFUtilities.unlockDocument(pdf: pdf, documentPasswordInfo: documentPasswordInfo) : pdf
        
        if let pageCount = pdf?.numberOfPages  {
            for index in 0...pageCount {
                if let page = pdf?.page(at: index) {
                    if let img = pdfPageToImage(page: page) {
                        output.append(img)
                    }
                }
            }
            
            return output
        }
        
        return nil
    }
```

**And it works!**

Good job, I think you're expert in Objective C and you're not familiar with Optionals :)
I will Send you a push request later.

**Comment by ronysteel** [comment]
But also, if pin is wrong, it open an empty document.
Needed to create an error type. I think
